/* Automatically generated by gen_art_config */

/*
#define ART_SIZEOF_CHAR 1
#define ART_SIZEOF_SHORT 2
#define ART_SIZEOF_INT 4
#define ART_SIZEOF_LONG 4
*/

typedef uint8_t art_u8;
typedef uint16_t art_u16;
typedef uint32_t art_u32;

