/*--------------------------------------------------------------------------
 * This file is autogenerated from config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
 
#ifndef __RECORE_SDK_CONFIG_H__ 
#define __RECORE_SDK_CONFIG_H__ 


/* stdlib.h */
#define HAVE_STDLIB_H 1 


/* inttypes.h */
#define HAVE_INTTYPES_H 1


/* sys/types.h */
#define HAVE_SYS_TYPES_H 1


/* stddef.h */
#define HAVE_STDDEF_H 1


/* stdbool.h */
#define HAVE_STDBOOL_H 1


/* stdint.h */
#define HAVE_STDINT_H 1


/* limits.h */
#define HAVE_LIMITS_H 1


/* float.h */
#define HAVE_FLOAT_H 1


/* mach/mach_time.h */
#define HAVE_MACH_MACH_TIME_H 1


/* sys/time.h */
#define HAVE_SYS_TIME_H 1


/* time.h */
#define HAVE_TIME_H 1


/* sys/time.h */
#define HAVE_SYS_TIME_H 1


/* locale.h */
#define HAVE_LOCALE_H 1


/* sys/stat.h */
#define HAVE_SYS_STAT_H 1


/* fcntl.h */
#define HAVE_FCNTL_H 1


/* pthread.h */
#define HAVE_PTHREAD_H 1


/* sys/resource.h */
#define HAVE_SYS_RESOURCE_H 1


/* direct.h */
/* #undef HAVE_DIRECT_H */


/* wchar.h */
#define HAVE_WCHAR_H 1


/* memory.h */
#define HAVE_MEMORY_H 1


/* string.h */
#define HAVE_STRING_H 1


/* math.h */
#define HAVE_MATH_H 1


/* malloc.h */ 
/* #undef HAVE_MALLOC_H */


/* byteswap.h */
/* #undef HAVE_BYTESWAP_H */


/* lua.h */
/* #undef HAVE_LUA_H */


/* lualib.h */
/* #undef HAVE_LUA_LIB_H */


/* errno.h */
#define HAVE_ERRNO_H 1


/* sys/errno.h */
#define HAVE_SYS_ERRNO_H 1

/* setjmp.h */
#define HAVE_SETJMP_H 1


/* unistd.h */
#define HAVE_UNISTD_H 1


/* zlib.h */
#define HAVE_ZLIB_H 1


/* bzlib.h */
#define HAVE_BZLIB_H 1


/* png.h */
/* #undef HAVE_PNG_H */


/* jpeglib.h */
/* #undef HAVE_JPEGLIB_H */


/* openjpeg/openjpeg.h */
/* #undef HAVE_OPENJPEG_OPENJPEG_H */


/* openjpeg.h */
/* #undef HAVE_OPENJPEG */


/* webp/types.h */
/* #undef HAVE_WEBP_TYPES_H */


/* webp/mux.h */
/* #undef HAVE_WEBP_MUX_H */


/* webp/decode.h */
/* #undef HAVE_WEBP_DECODE_H */


/* webp/encode.h */
/* #undef HAVE_WEBP_ENCODE_H */


/* sqlite3.h */
#define HAVE_SQLITE3_H 1


/* libpq-fe.h */
#define HAVE_LIBPQ_FE_H 1


/* postgresql/libpq-fe.h */
/* #undef HAVE_POSTGRESQL_LIBPQ_FE_H */


/* ft2build.h */
/* #undef HAVE_FT2BUILD_H */


/* freetype/freetype.h */
/* #undef HAVE_FREETYPE_FREETYPE_H */


/* freetype2/freetype/freetype.h */
/* #undef HAVE_FREETYPE2_FREETYPE_FREETYPE_H */


/* lzma/lzma.h */
/* #undef HAVE_LZMA_LZMA_H */


/* lzma.h */
/* #undef HAVE_LZMA_H */


/* LzmaLib.h */
/* #undef HAVE_LZMALIB_H */


/* vorbis/codec.h */
/* #undef HAVE_VORBIS_CODEC_H */


/* vorbis/vorbisfile.h */
/* #undef HAVE_VORBIS_VORBISFILE_H */


/* theora/theoradec.h */
/* #undef HAVE_THEORA_THEORADEC_H */


/* tremor/ivorbiscodec.h */
/* #undef HAVE_TREMOR_IVORBISCODEC_H */


/* tremor/ivorbisfile.h */
/* #undef HAVE_TREMOR_IVORBISFILE_H */


/* curl/curl.h */
#define HAVE_CURL_CURL_H 1


/* ogg/ogg.h */
/* #undef HAVE_OGG_OGG_H */


/* jni.h */
/* #undef HAVE_JNI_H */


/* arm_neon.h */
/* #undef HAVE_ARM_NEON_H */


/* OpenGL headers */
/* gl/gl.h */
/* #undef HAVE_GL_GL_H */


/* gl/glu.h */
/* #undef HAVE_GL_GLU_H */


/* OpenGL/OpenGL.h */
#define HAVE_OPENGL_OPENGL_H 1


/* OpenGL/gl.h */
#define HAVE_OPENGL_GL_H 1


/* OpenGL/glu.h */ 
#define HAVE_OPENGL_GLU_H 1


/* OpenGLES/ES1/gl.h */
/* #undef HAVE_OPENGLES_ES1_GL_H */


/* OpenGLES/ES1/glext.h */
/* #undef HAVE_OPENGLES_ES1_GLEXT_H */


/* OpenGLES/ES2/gl.h */
/* #undef HAVE_OPENGLES_ES2_GL_H */


/* OpenGLES/ES2/glext.h */
/* #undef HAVE_OPENGLES_ES2_GLEXT_H */


/* GL/gl.h */
/* #undef HAVE__GL_GL_H */


/* GL/glu.h */
/* #undef HAVE__GL_GLU_H */


/* GL/glut.h */
/* #undef HAVE__GL_GLUT_H */


/* GLES/gl.h */
/* #undef HAVE_GLES_GL_H */


/* GLES/glext.h */
/* #undef HAVE_GLES_GLEXT_H */

/* gl.h */
/* #undef HAVE_GL_H */


/* glext.h */
/* #undef HAVE_GLEXT_H */


/* glmacro.h */
/* #undef HAVE_GLMACRO_H */


/* dispatch/dispatch.h */
#define HAVE_DISPATCH_DISPATCH_H 1


/* includes */
#if defined(HAVE_SYS_TYPES_H)
#include <sys/types.h>
#endif

#if defined(HAVE_MALLOC_H)
#include <malloc.h>
#endif


/* sizes */
/* int8_t */
#define SIZEOF_INT8_T 1

/* uint8_t */
#define SIZEOF_UINT8_T 1

/* int16_t */
#define SIZEOF_INT16_T 2

/* uint16_t */
#define SIZEOF_UINT16_T 2

/* int32_t */
#define SIZEOF_INT32_T 4

/* uint32_t */
#define SIZEOF_UINT32_T 4

/* int64_t */
#define SIZEOF_INT64_T 8

/* uint64_t */
#define SIZEOF_UINT64_T 8

/* uintptr_t */
#define SIZEOF_UINTPTR_T 8

/* char */
#define SIZEOF_CHAR 1

/* long int */
#define SIZEOF_LONG_INT 8

/* long long int */
#define SIZEOF_LONG_LONG_INT 8

/* float */
#define SIZEOF_FLOAT 4

/* double */
#define SIZEOF_DOUBLE 8 

/* long double */
#define SIZEOF_LONG_DOUBLE 16 

/* bool */
#define SIZEOF_BOOL 1 


/* float128 */
#define HAVE_FLOAT128 1 
#if defined(HAVE_FLOAT128)
typedef long double REFloat128; 
#define REFLOAT128_DEFINED 1
#endif


/* int128, uint128 */
//#define HAVE_INTEGERS128 1 
//#if defined(HAVE_INTEGERS128) 
//typedef __int128_t REInt128;
//typedef __uint128_t REUInt128;
//#endif



/* structures */
/* struct stat */
#define HAVE_STRUCT_STAT 1 


/* struct _stat */
/* #undef HAVE_STRUCT__STAT */



/* functions */
/* posix_memalign */
#define HAVE_FUNCTION_POSIX_MEMALIGN 1 


/* usleep */
#define HAVE_FUNCTION_USLEEP 1 


/* getrlimit */
#define HAVE_FUNCTION_GETRLIMIT 1 


/* pthread_attr_setscope */
#define HAVE_FUNCTION_PTHREAD_ATTR_SETSCOPE 1 


/* pthread_attr_setstacksize */
#define HAVE_FUNCTION_PTHREAD_ATTR_SETSTACKSIZE 1 


/* _stat */
/* #undef HAVE_FUNCTION__STAT */


/* stat */
#define HAVE_FUNCTION_STAT 1 


/* _wstat */
/* #undef HAVE_FUNCTION__WSTAT */

/* access */
#define HAVE_FUNCTION_ACCESS  1 


/* _mkdir */
/* #undef HAVE_FUNCTION__MKDIR */


/* mkdir */
#define HAVE_FUNCTION_MKDIR 1 


/* _wmkdir */
/* #undef HAVE_FUNCTION__WMKDIR */


/* clock_gettime */
/* #undef HAVE_FUNCTION_CLOCK_GETTIME */


/* fabsf */
#define HAVE_FUNCTION_FABSF 1 


/* fabs */
#define HAVE_FUNCTION_FABS 1 


/* floorf */
#define HAVE_FUNCTION_FLOORF 1 


/* floor */
#define HAVE_FUNCTION_FLOOR 1 


/* powf */
#define HAVE_FUNCTION_POWF 1 


/* pow */
#define HAVE_FUNCTION_POW 1 


/* cosf */
#define HAVE_FUNCTION_COSF 1 


/* cos */
#define HAVE_FUNCTION_COS 1 


/* sinf */
#define HAVE_FUNCTION_SINF 1 


/* sin */
#define HAVE_FUNCTION_SIN 1 


/* sqrtf */
#define HAVE_FUNCTION_SQRTF 1 


/* sqrt */
#define HAVE_FUNCTION_SQRT 1 


/* _wfopen */
/* #undef HAVE_FUNCTION__WFOPEN */


/* _wfopen_s */
/* #undef HAVE_FUNCTION__WFOPEN_S */


/* fopen_s */
/* #undef HAVE_FUNCTION_FOPEN_S */


/* sscanf_s */
/* #undef HAVE_FUNCTION_SSCANF_S */


/* clock_gettime */
/* #undef HAVE_FUNCTION_CLOCK_GETTIME */


/* dispatch_sync */
#define HAVE_FUNCTION_DISPATCH_SYNC 1


/* dispatch_async */
#define HAVE_FUNCTION_DISPATCH_ASYNC 1


/* dispatch_get_global_queue */
#define HAVE_FUNCTION_DISPATCH_GET_GLOBAL_QUEUE 1


/* dispatch_after */
#define HAVE_FUNCTION_DISPATCH_AFTER 1



/* OS type */
/* #undef __RE_OS_WINDOWS__ */

#define __RE_OS_IPHONE__ 1

/* #undef __RE_OS_MACOSX__ */

/* #undef __RE_OS_LINUX__ */

/* #undef __RE_OS_ANDROID__ */

/* #undef __RE_OS_BADA__ */



/* functionality */
/* Disables zlib compression/decompression for REZLIBCompression. */
/* #undef __RE_RECORE_NO_ZLIB_COMPRESSION_SUPPORT__ */


/* Disables lzma compression/decompression for RELZMACompression. */
/* #undef __RE_RECORE_NO_LZMA_COMPRESSION_SUPPORT__ */


/* Disables reading(decoding)/writing(encode) PNG image format. */
/* #undef __RE_RECORE_NO_PNG_IMAGE_SUPPORT__ */


/* Disables reading(decoding) JPEG image format. */
/* #undef __RE_RECORE_NO_JPEG_IMAGE_SUPPORT__ */


/* Disables reading(decoding)/writing(encode) WEBP image format. */
/* #undef __RE_RECORE_NO_WEBP_IMAGE_SUPPORT__ */


/* Disables REFloat16 as 16 bit float, in this case type REFloat16 will be defined as REFloat32 (32 bit float) for compability. */
/* #undef __RE_RECORE_NO_FLOAT16_SUPPORT__ */


/* Disables yuv to rgb/a color conversion. Class REYUVtoRGB will do nothing. */
/* #undef __RE_CORE_NO_YUV_TO_RGB_CONVERSION__ */


/* Disables reading/writing to SQLite database. */
/* #undef __RE_CORE_NO_SQLITE_DATABASE_SUPPORT__ */


/* Disables reading/writing to PostgreSQL database. */
/* #undef __RE_CORE_NO_POSTGRESQL_DATABASE_SUPPORT__ */


/* Removes from REString functionality witch converts special symbols to it's html presentation and back. */ 
/* #undef __RE_RECORE_NO_STRING_DECODE_ENCODE_SPECIAL_HTML_CHARACTERS__ */


/* Disables objects initialzation from url */
/* #undef __RE_RECORE_NO_LOAD_FROM_URL__ */


#endif /* __RECORE_SDK_CONFIG_H__ */



